import re

with open('app/src/app.css', 'r') as f:
    content = f.read()

# Find all blocks like @media (max-width: 1024px) { ... }
# Note: CSS blocks can have nested braces, so regex is tricky.
# We will use a simple bracket counter.

def extract_media_blocks(text, media_query):
    results = []
    idx = 0
    while True:
        idx = text.find(media_query, idx)
        if idx == -1:
            break
        start_brace = text.find('{', idx)
        if start_brace == -1:
            break
        
        brace_count = 1
        end_brace = start_brace + 1
        while end_brace < len(text) and brace_count > 0:
            if text[end_brace] == '{':
                brace_count += 1
            elif text[end_brace] == '}':
                brace_count -= 1
            end_brace += 1
            
        if brace_count == 0:
            results.append(text[start_brace+1:end_brace-1])
        idx = end_brace
    return results

blocks1024 = extract_media_blocks(content, "@media (max-width: 1024px)")
blocks640 = extract_media_blocks(content, "@media (max-width: 640px)")
blocks600 = extract_media_blocks(content, "@media (max-width: 600px)")

out = "\n/* --- AUTOGENERATED FORCE MOBILE CLASSES --- */\n"

def prefix_rules(block, prefix):
    # Quick hack: insert prefix before every selector that isn't inside a block
    # Actually, simpler: we don't have nested at-rules here. 
    # Just prefix every selector.
    # But it's easier to just wrap them in a pseudo-element or class?
    # Standard CSS doesn't support nesting yet in all browsers unless compiled.
    # Wait, Vite uses PostCSS which supports nesting if configured.
    pass

# Wait, instead of parsing and prefixing every rule, which is error-prone,
# SvelteKit with Vite natively supports CSS nesting (PostCSS preset env)!
# So we can just wrap the blocks in `.force-mobile { ... }` !

for block in blocks1024 + blocks640 + blocks600:
    out += f"\n.force-mobile {{\n{block}\n}}\n"

with open('app/src/app.css', 'a') as f:
    f.write(out)

print("Done appending nested force-mobile classes!")
